version: "3"

services:
  db:
    image: mariadb
    restart: always
    container_name: pinger_server_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8085:8080
  pinger_server:
    restart: always
    container_name: pinger_server
    image: daveplsno/pinger_server:devel
    build: .
    command: python manage.py runserver 0.0.0.0:10000
    volumes:
      - ./data:/code
    ports:
      - "10000:10000"
    depends_on:
      - db
  grafana:
    restart: always
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ../grafana/data:/data
    ports:
      - "3001:3000"
    depends_on:
      - db