# Generated by Django 3.0.5 on 2020-04-18 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dns_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('ttl_time', models.CharField(blank=True, max_length=255)),
                ('protocol', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('last_state', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'dns_results',
            },
        ),
        migrations.CreateModel(
            name='icmp_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('icmp_size', models.IntegerField(default=0, null=True)),
                ('icmp_interval', models.IntegerField(default=0, null=True)),
                ('icmp_count', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rtt_avg', models.CharField(max_length=255, null=True)),
                ('rtt_max', models.CharField(max_length=255, null=True)),
                ('rtt_min', models.CharField(max_length=255, null=True)),
                ('packetloss', models.IntegerField(default=0)),
                ('received', models.IntegerField(default=0)),
                ('transmitted', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('results', models.CharField(max_length=1000, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'icmp_results',
            },
        ),
        migrations.CreateModel(
            name='targets',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('icmp', models.BooleanField(default=False)),
                ('dns', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=255, null=True)),
                ('icmp_size', models.IntegerField(default=500, null=True)),
                ('icmp_interval', models.IntegerField(default=1, null=True)),
                ('icmp_count', models.IntegerField(default=5, null=True)),
            ],
            options={
                'verbose_name_plural': ('targets',),
            },
        ),
    ]
