# Generated by Django 3.0.5 on 2020-04-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targets',
            options={'verbose_name_plural': 'targets'},
        ),
    ]
