version: "3.8"

services:
  pinger_frontend:
    restart: always
    container_name: pinger_frontend
    image: node:lts-slim
    #build: .
    working_dir: /app/pong
    command: yarn start
    volumes:
      - ./data:/app
    ports:
      - "3000:3000"
      #- "5000:5000"
    stdin_open: true
